name: customer-portal-deploy workflow
on:
  repository_dispatch:
    types: [main-push-event]
jobs:
  customerPortalMainPushEvent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
      - run: git rm *.js; git rm *.css; git rm *.html; git rm *.txt; git rm -rf assets
      - name: Checkout customer-portal repository
        uses: actions/checkout@v3
        with:
          repository: onegridxyz/customer-portal
          path: ./customer-portal/
      - name: Install dependencies & compile
        run: cd customer-portal; npm install; npm run build;
      - run: ls -l
      - run: cp -af customer-portal/dist/customer-portal/* ./; rm -rf customer-portal
      - run: ls -l
      - name: Commit latest release
        run: |
          git config user.name 'Truong Le'
          git config user.email 'travistrle@gmail.com'
          git add .
          git commit -am "latest update"
          git push
      # - name: Commit to main branch
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     author_name: Truong Le
      #     author_email: travistrle@gmail.com
      #     message: "Update latest version"
      #     add: "*.*"
